server:
  #port: 8084  cuando dejamos 0 utiliza random
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
info:
  application:
    name: catalog-service
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true   #ver si lleva false, quien consume a quien
    serviceUrl:
      defaulZone: http://localhost:8761/eureka/