server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EugeniaB8315/BackEnd_ConfigServer
          default-label: main
          force-pull: true
          search-paths: configData
        bootstrap: true